### **ANN 回歸Regression**
**預測未知資料的趨勢** \
-> **預測發電廠在未來一小時產生的發電功率**

In [42]:
import numpy as np
import pandas as pd
import tensorflow as tf
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import MinMaxScaler



### **資料前處理**

欄位 :  \
AT : Average Ambient Temperature \
V : Exhuast Vacuum  \
AP : AMbient Pressure \
RH : Relative Humidity \
PE : Preedicted Electrical energy output 

In [38]:
# 讀取資料集
data_df = pd.read_excel('D:\DeepLearning_Knowledge\CCPP\Folds5x2_pp.xlsx')
data_df

AT      V       AP     RH      PE
0     14.96  41.76  1024.07  73.17  463.26
1     25.18  62.96  1020.04  59.08  444.37
2      5.11  39.40  1012.16  92.14  488.56
3     20.86  57.32  1010.24  76.64  446.48
4     10.82  37.50  1009.23  96.62  473.90
...     ...    ...      ...    ...     ...
9563  16.65  49.69  1014.01  91.00  460.03
9564  13.19  39.18  1023.67  66.78  469.62
9565  31.32  74.33  1012.92  36.48  429.57
9566  24.48  69.45  1013.86  62.39  435.74
9567  21.60  62.52  1017.23  67.87  453.28

[9568 rows x 5 columns]

In [41]:
# 定義特徵X、標籤Y
# 當我在這個特徵X 下， 我得到的發電功率為Y
# iloc = numpy選取範圍 [第幾筆資料，第幾個特徵]
data_X = data_df.iloc[:,:-1].values
print(data_X, type(data_X), data_X.shape)
data_Y = data_df.iloc[:, -1].values
print(data_Y, type(data_Y), data_Y.shape)

[[  14.96   41.76 1024.07   73.17]
 [  25.18   62.96 1020.04   59.08]
 [   5.11   39.4  1012.16   92.14]
 ...
 [  31.32   74.33 1012.92   36.48]
 [  24.48   69.45 1013.86   62.39]
 [  21.6    62.52 1017.23   67.87]] <class 'numpy.ndarray'> (9568, 4)
[463.26 444.37 488.56 ... 429.57 435.74 453.28] <class 'numpy.ndarray'> (9568,)


In [48]:
# 隨機切割資料集 fomr sci-kit learn
data_X_train, data_X_test, data_Y_train, data_Y_test = train_test_split(data_X, data_Y, train_size= 0.2, random_state= 42)
print(type(data_X_train), data_X_train.shape)
print(type(data_X_test), data_X_test.shape)
print(type(data_Y_train), data_Y_train.shape)
print(type(data_Y_test), data_Y_test.shape)


<class 'numpy.ndarray'> (1913, 4)
<class 'numpy.ndarray'> (7655, 4)
<class 'numpy.ndarray'> (1913,)
<class 'numpy.ndarray'> (7655,)


In [47]:
data_X_train

array([[  14.44,   39.  , 1017.06,   76.02],
       [  13.61,   41.16, 1020.49,   75.09],
       [  24.6 ,   57.85, 1012.92,   69.56],
       ...,
       [  27.79,   69.23, 1012.86,   45.71],
       [  12.26,   41.5 , 1014.87,   89.41],
       [  11.75,   40.55, 1018.09,   97.7 ]])